"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Person_1 = require("./classes/Person");
var Student_1 = require("./classes/Student");
var Subject_1 = require("./classes/Subject");
var Teacher_1 = require("./classes/Teacher");
var person1 = new Person_1.default('Écio', new Date('1991/07/24'));
var student1 = new Student_1.default('Britney', new Date('1981/12/02'));
var subject1 = new Subject_1.default('Math');
var subject2 = new Subject_1.default('History');
var subject3 = new Subject_1.default('Philosophy');
var teacher1 = new Teacher_1.default('Marcia', new Date('1992/03/16'), 2003, subject1);
student1.grades = [10, 8, 9, 10];
student1.workpapers = [10, 10];
console.log(person1);
console.log(student1);
console.log(student1.sum());
console.log(student1.average());
console.log(subject1);
console.log(subject2);
console.log(subject3);
console.log(teacher1);
