"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Person_1 = require("./school/Person");
var Student_1 = require("./school/Student");
var Subject_1 = require("./school/Subject");
var Teacher_1 = require("./school/Teacher");
var person1 = new Person_1.default('Écio', new Date('1991/07/24'));
var student1 = new Student_1.default('Marcia', new Date('1992/03/16'));
var subject1 = new Subject_1.default('Dance');
var teacher1 = new Teacher_1.default('Britney', new Date('1981/12/02'), 2000, subject1);
student1.examGrades = [10, 8, 9, 10];
student1.paperGrades = [10, 10];
console.log(person1);
console.log(student1);
console.log(student1.sumGrades());
console.log(student1.gradesAverage());
console.log(subject1);
console.log(teacher1);
